builds:
- env:
    - CGO_ENABLED=0

dockers:
  - dockerfile: Dockerfile-goreleaser
    binaries:
    - crashlytics2humio
    image_templates:
    - "quay.io/lunarway/crashlytics2humio:latest"
    - "quay.io/lunarway/crashlytics2humio:v{{ .Major }}"
    - "quay.io/lunarway/crashlytics2humio:v{{ .Major }}.{{ .Minor }}"
    - "quay.io/lunarway/crashlytics2humio:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

archive:
  format: binary
  name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
